services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: sinan-api:latest
    container_name: sinan-app
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - sinan-network
    mem_limit: 1g
    cpus: 1.2

  postgres:
    image: cgr.dev/chainguard/postgres:latest
    container_name: sinan-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - sinan-network
    mem_limit: 800m
    cpus: 1.2
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

volumes:
  postgres_data:

networks:
  sinan-network:
    driver: bridge