spring.application.name=sinan-api

# Configuração do Banco de Dados
spring.datasource.url=${URL_DB}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Connection Pool (HikariCP)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=${DDL_AUTO}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.default_batch_fetch_size=100

# Servidor
server.port=8080
server.address=0.0.0.0